### ISSUE TITLE
MacOS IP not showing

### ISSUE THREAD

**Issue by ShafiqSadat** [mrijoo/RDP#2]

**Comment by ShafiqSadat** [comment]
fixed sorry

**Comment by eqixcx** [comment]
@ShafiqSadat What caused this? I'm having the same issue lmao--

**Comment by mrijoo** [comment]
![IP-·-eqixcx-RDP-3d964bf (1)](https://user-images.githubusercontent.com/77200341/124364618-d4d15780-dc6c-11eb-9a3d-6c5aeae5b162.png)

@eqixcx ???
