### ISSUE TITLE
What is the root password for Ubuntu?

### ISSUE THREAD

**Issue by monroefisher86** [mrijoo/RDP#3]
Sorry, can't seem to find it :/
Do you know what the password is?

**Comment by mrijoo** [comment]
for now I don't know. you can use (sudo useradd username && sudo passwd username) to add a new user.

**Comment by sujkoj** [comment]
if you want to use it for ssh use https://github.com/mrijoo/SSH

**Comment by mrijoo** [comment]
if you want to use it for ssh use https://github.com/mrijoo/SSH

**Comment by monroefisher86** [comment]
Thanks, useful info :)
Also, it seems like doing what I needed (install from snap store `sudo snap install *software*` ) through terminal works without pass.

**Comment by mrijoo** [comment]
do everything through the terminal with the prefix sudo then everything runs without a password.
